/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Config,
  Describe,
  Status,
  Whoami,
} from '../models/index';
import {
    ConfigFromJSON,
    ConfigToJSON,
    DescribeFromJSON,
    DescribeToJSON,
    StatusFromJSON,
    StatusToJSON,
    WhoamiFromJSON,
    WhoamiToJSON,
} from '../models/index';

/**
 * MetaApi - interface
 * 
 * @export
 * @interface MetaApiInterface
 */
export interface MetaApiInterface {
    /**
     * The endpoints this deployment serves, with the credential each needs. It takes no key, which is what makes it the way to check an address before configuring one. It is generated from the same table the routes are, so it cannot omit a route.
     * @summary This API\'s own contract
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetaApiInterface
     */
    describeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Describe>>;

    /**
     * The endpoints this deployment serves, with the credential each needs. It takes no key, which is what makes it the way to check an address before configuring one. It is generated from the same table the routes are, so it cannot omit a route.
     * This API\'s own contract
     */
    describe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Describe>;

    /**
     * What this deployment is: the interface version, the lifetimes it enforces, whether it manages users, and where it is served. The console reads it on load to decide what to offer.
     * @summary The deployment\'s shape
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetaApiInterface
     */
    getConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Config>>;

    /**
     * What this deployment is: the interface version, the lifetimes it enforces, whether it manages users, and where it is served. The console reads it on load to decide what to offer.
     * The deployment\'s shape
     */
    getConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Config>;

    /**
     * Answers as long as the process is up. It does not check the cluster, so it is the wrong probe for \"can this control plane do its job\".
     * @summary Liveness
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetaApiInterface
     */
    healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Status>>;

    /**
     * Answers as long as the process is up. It does not check the cluster, so it is the wrong probe for \"can this control plane do its job\".
     * Liveness
     */
    health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Status>;

    /**
     * Answers 200 when the control plane can reach a cluster and 503 when it cannot, which is the difference between \"running\" and \"working\".
     * @summary Readiness
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetaApiInterface
     */
    readyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Status>>;

    /**
     * Answers 200 when the control plane can reach a cluster and 503 when it cannot, which is the difference between \"running\" and \"working\".
     * Readiness
     */
    ready(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Status>;

    /**
     * Whether the caller holds the administrator\'s key or a user\'s, and for a user, who they are. The console reads it to decide between its two views.
     * @summary Which key this is
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetaApiInterface
     */
    whoamiRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Whoami>>;

    /**
     * Whether the caller holds the administrator\'s key or a user\'s, and for a user, who they are. The console reads it to decide between its two views.
     * Which key this is
     */
    whoami(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Whoami>;

}

/**
 * 
 */
export class MetaApi extends runtime.BaseAPI implements MetaApiInterface {

    /**
     * The endpoints this deployment serves, with the credential each needs. It takes no key, which is what makes it the way to check an address before configuring one. It is generated from the same table the routes are, so it cannot omit a route.
     * This API\'s own contract
     */
    async describeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Describe>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/describe`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DescribeFromJSON(jsonValue));
    }

    /**
     * The endpoints this deployment serves, with the credential each needs. It takes no key, which is what makes it the way to check an address before configuring one. It is generated from the same table the routes are, so it cannot omit a route.
     * This API\'s own contract
     */
    async describe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Describe> {
        const response = await this.describeRaw(initOverrides);
        return await response.value();
    }

    /**
     * What this deployment is: the interface version, the lifetimes it enforces, whether it manages users, and where it is served. The console reads it on load to decide what to offer.
     * The deployment\'s shape
     */
    async getConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Config>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/config`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigFromJSON(jsonValue));
    }

    /**
     * What this deployment is: the interface version, the lifetimes it enforces, whether it manages users, and where it is served. The console reads it on load to decide what to offer.
     * The deployment\'s shape
     */
    async getConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Config> {
        const response = await this.getConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Answers as long as the process is up. It does not check the cluster, so it is the wrong probe for \"can this control plane do its job\".
     * Liveness
     */
    async healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Status>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/healthz`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusFromJSON(jsonValue));
    }

    /**
     * Answers as long as the process is up. It does not check the cluster, so it is the wrong probe for \"can this control plane do its job\".
     * Liveness
     */
    async health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Status> {
        const response = await this.healthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Answers 200 when the control plane can reach a cluster and 503 when it cannot, which is the difference between \"running\" and \"working\".
     * Readiness
     */
    async readyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Status>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/readyz`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusFromJSON(jsonValue));
    }

    /**
     * Answers 200 when the control plane can reach a cluster and 503 when it cannot, which is the difference between \"running\" and \"working\".
     * Readiness
     */
    async ready(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Status> {
        const response = await this.readyRaw(initOverrides);
        return await response.value();
    }

    /**
     * Whether the caller holds the administrator\'s key or a user\'s, and for a user, who they are. The console reads it to decide between its two views.
     * Which key this is
     */
    async whoamiRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Whoami>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/whoami`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WhoamiFromJSON(jsonValue));
    }

    /**
     * Whether the caller holds the administrator\'s key or a user\'s, and for a user, who they are. The console reads it to decide between its two views.
     * Which key this is
     */
    async whoami(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Whoami> {
        const response = await this.whoamiRaw(initOverrides);
        return await response.value();
    }

}
