/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSandboxRequest,
  DeleteSandbox200Response,
  GetSandboxLogs200Response,
  Overview,
  RenewSandboxRequest,
  Sandbox,
  SandboxList,
  Template,
  TemplateList,
} from '../models/index';
import {
    CreateSandboxRequestFromJSON,
    CreateSandboxRequestToJSON,
    DeleteSandbox200ResponseFromJSON,
    DeleteSandbox200ResponseToJSON,
    GetSandboxLogs200ResponseFromJSON,
    GetSandboxLogs200ResponseToJSON,
    OverviewFromJSON,
    OverviewToJSON,
    RenewSandboxRequestFromJSON,
    RenewSandboxRequestToJSON,
    SandboxFromJSON,
    SandboxToJSON,
    SandboxListFromJSON,
    SandboxListToJSON,
    TemplateFromJSON,
    TemplateToJSON,
    TemplateListFromJSON,
    TemplateListToJSON,
} from '../models/index';

export interface SandboxesApiCreateSandboxOperationRequest {
    createSandboxRequest: CreateSandboxRequest;
}

export interface SandboxesApiDeleteSandboxRequest {
    id: string;
}

export interface SandboxesApiGetCatalogEntryRequest {
    id: string;
}

export interface SandboxesApiGetSandboxRequest {
    id: string;
}

export interface SandboxesApiGetSandboxLogsRequest {
    id: string;
    tail?: number;
}

export interface SandboxesApiProxyToSandboxRequest {
    id: string;
    port: string;
}

export interface SandboxesApiRenewSandboxOperationRequest {
    id: string;
    renewSandboxRequest: RenewSandboxRequest;
}

/**
 * SandboxesApi - interface
 * 
 * @export
 * @interface SandboxesApiInterface
 */
export interface SandboxesApiInterface {
    /**
     * 
     * @summary Create one
     * @param {CreateSandboxRequest} createSandboxRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApiInterface
     */
    createSandboxRaw(requestParameters: SandboxesApiCreateSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sandbox>>;

    /**
     * Create one
     */
    createSandbox(requestParameters: SandboxesApiCreateSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sandbox>;

    /**
     * Everything in it goes too. A sandbox is a namespace, so this is one operation rather than a list of objects to get right.
     * @summary Delete one
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApiInterface
     */
    deleteSandboxRaw(requestParameters: SandboxesApiDeleteSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteSandbox200Response>>;

    /**
     * Everything in it goes too. A sandbox is a namespace, so this is one operation rather than a list of objects to get right.
     * Delete one
     */
    deleteSandbox(requestParameters: SandboxesApiDeleteSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteSandbox200Response>;

    /**
     * 
     * @summary One template
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApiInterface
     */
    getCatalogEntryRaw(requestParameters: SandboxesApiGetCatalogEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Template>>;

    /**
     * One template
     */
    getCatalogEntry(requestParameters: SandboxesApiGetCatalogEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Template>;

    /**
     * What is running and what it is: how many sandboxes exist, and how they break down by state and template.
     * @summary Counts of sandboxes by state and template
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApiInterface
     */
    getOverviewRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Overview>>;

    /**
     * What is running and what it is: how many sandboxes exist, and how they break down by state and template.
     * Counts of sandboxes by state and template
     */
    getOverview(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Overview>;

    /**
     * 
     * @summary One sandbox
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApiInterface
     */
    getSandboxRaw(requestParameters: SandboxesApiGetSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sandbox>>;

    /**
     * One sandbox
     */
    getSandbox(requestParameters: SandboxesApiGetSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sandbox>;

    /**
     * A sandbox whose container is still being created answers 409: there is nothing to read yet, which is the ordinary state moments after a create rather than a failure.
     * @summary The tail of a sandbox\'s output
     * @param {string} id 
     * @param {number} [tail] how many lines to return; 200 when omitted
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApiInterface
     */
    getSandboxLogsRaw(requestParameters: SandboxesApiGetSandboxLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSandboxLogs200Response>>;

    /**
     * A sandbox whose container is still being created answers 409: there is nothing to read yet, which is the ordinary state moments after a create rather than a failure.
     * The tail of a sandbox\'s output
     */
    getSandboxLogs(requestParameters: SandboxesApiGetSandboxLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSandboxLogs200Response>;

    /**
     * 
     * @summary The templates a sandbox can be created from
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApiInterface
     */
    listCatalogRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplateList>>;

    /**
     * The templates a sandbox can be created from
     */
    listCatalog(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplateList>;

    /**
     * 
     * @summary Every sandbox you may see
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApiInterface
     */
    listSandboxesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SandboxList>>;

    /**
     * Every sandbox you may see
     */
    listSandboxes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SandboxList>;

    /**
     * The data plane: everything under this prefix is forwarded to the sandbox\'s container. What comes back is whatever the sandbox serves — HTML, JSON, a file — so it is not a typed endpoint and the SDK exposes the address rather than a method. A browser navigation cannot set a header, which is why the key is also accepted in the query string.
     * @summary Proxy to a sandbox\'s own port
     * @param {string} id 
     * @param {string} port 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApiInterface
     */
    proxyToSandboxRaw(requestParameters: SandboxesApiProxyToSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * The data plane: everything under this prefix is forwarded to the sandbox\'s container. What comes back is whatever the sandbox serves — HTML, JSON, a file — so it is not a typed endpoint and the SDK exposes the address rather than a method. A browser navigation cannot set a header, which is why the key is also accepted in the query string.
     * Proxy to a sandbox\'s own port
     */
    proxyToSandbox(requestParameters: SandboxesApiProxyToSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * A ttl of \"0\" removes the expiry entirely, which is how a sandbox someone is working in is kept from disappearing.
     * @summary Reset a sandbox\'s lifetime, measured from now
     * @param {string} id 
     * @param {RenewSandboxRequest} renewSandboxRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApiInterface
     */
    renewSandboxRaw(requestParameters: SandboxesApiRenewSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sandbox>>;

    /**
     * A ttl of \"0\" removes the expiry entirely, which is how a sandbox someone is working in is kept from disappearing.
     * Reset a sandbox\'s lifetime, measured from now
     */
    renewSandbox(requestParameters: SandboxesApiRenewSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sandbox>;

}

/**
 * 
 */
export class SandboxesApi extends runtime.BaseAPI implements SandboxesApiInterface {

    /**
     * Create one
     */
    async createSandboxRaw(requestParameters: SandboxesApiCreateSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sandbox>> {
        if (requestParameters['createSandboxRequest'] == null) {
            throw new runtime.RequiredError(
                'createSandboxRequest',
                'Required parameter "createSandboxRequest" was null or undefined when calling createSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSandboxRequestToJSON(requestParameters['createSandboxRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxFromJSON(jsonValue));
    }

    /**
     * Create one
     */
    async createSandbox(requestParameters: SandboxesApiCreateSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sandbox> {
        const response = await this.createSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Everything in it goes too. A sandbox is a namespace, so this is one operation rather than a list of objects to get right.
     * Delete one
     */
    async deleteSandboxRaw(requestParameters: SandboxesApiDeleteSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteSandbox200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteSandbox200ResponseFromJSON(jsonValue));
    }

    /**
     * Everything in it goes too. A sandbox is a namespace, so this is one operation rather than a list of objects to get right.
     * Delete one
     */
    async deleteSandbox(requestParameters: SandboxesApiDeleteSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteSandbox200Response> {
        const response = await this.deleteSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * One template
     */
    async getCatalogEntryRaw(requestParameters: SandboxesApiGetCatalogEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Template>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCatalogEntry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/catalog/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateFromJSON(jsonValue));
    }

    /**
     * One template
     */
    async getCatalogEntry(requestParameters: SandboxesApiGetCatalogEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Template> {
        const response = await this.getCatalogEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * What is running and what it is: how many sandboxes exist, and how they break down by state and template.
     * Counts of sandboxes by state and template
     */
    async getOverviewRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Overview>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/overview`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OverviewFromJSON(jsonValue));
    }

    /**
     * What is running and what it is: how many sandboxes exist, and how they break down by state and template.
     * Counts of sandboxes by state and template
     */
    async getOverview(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Overview> {
        const response = await this.getOverviewRaw(initOverrides);
        return await response.value();
    }

    /**
     * One sandbox
     */
    async getSandboxRaw(requestParameters: SandboxesApiGetSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sandbox>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxFromJSON(jsonValue));
    }

    /**
     * One sandbox
     */
    async getSandbox(requestParameters: SandboxesApiGetSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sandbox> {
        const response = await this.getSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A sandbox whose container is still being created answers 409: there is nothing to read yet, which is the ordinary state moments after a create rather than a failure.
     * The tail of a sandbox\'s output
     */
    async getSandboxLogsRaw(requestParameters: SandboxesApiGetSandboxLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSandboxLogs200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSandboxLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tail'] != null) {
            queryParameters['tail'] = requestParameters['tail'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/logs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSandboxLogs200ResponseFromJSON(jsonValue));
    }

    /**
     * A sandbox whose container is still being created answers 409: there is nothing to read yet, which is the ordinary state moments after a create rather than a failure.
     * The tail of a sandbox\'s output
     */
    async getSandboxLogs(requestParameters: SandboxesApiGetSandboxLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSandboxLogs200Response> {
        const response = await this.getSandboxLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The templates a sandbox can be created from
     */
    async listCatalogRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplateList>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/catalog`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateListFromJSON(jsonValue));
    }

    /**
     * The templates a sandbox can be created from
     */
    async listCatalog(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplateList> {
        const response = await this.listCatalogRaw(initOverrides);
        return await response.value();
    }

    /**
     * Every sandbox you may see
     */
    async listSandboxesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SandboxList>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxListFromJSON(jsonValue));
    }

    /**
     * Every sandbox you may see
     */
    async listSandboxes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SandboxList> {
        const response = await this.listSandboxesRaw(initOverrides);
        return await response.value();
    }

    /**
     * The data plane: everything under this prefix is forwarded to the sandbox\'s container. What comes back is whatever the sandbox serves — HTML, JSON, a file — so it is not a typed endpoint and the SDK exposes the address rather than a method. A browser navigation cannot set a header, which is why the key is also accepted in the query string.
     * Proxy to a sandbox\'s own port
     */
    async proxyToSandboxRaw(requestParameters: SandboxesApiProxyToSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling proxyToSandbox().'
            );
        }

        if (requestParameters['port'] == null) {
            throw new runtime.RequiredError(
                'port',
                'Required parameter "port" was null or undefined when calling proxyToSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["key"] = await this.configuration.apiKey("key"); // ApiKeyQuery authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/sandbox/{id}/{port}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"port"}}`, encodeURIComponent(String(requestParameters['port'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * The data plane: everything under this prefix is forwarded to the sandbox\'s container. What comes back is whatever the sandbox serves — HTML, JSON, a file — so it is not a typed endpoint and the SDK exposes the address rather than a method. A browser navigation cannot set a header, which is why the key is also accepted in the query string.
     * Proxy to a sandbox\'s own port
     */
    async proxyToSandbox(requestParameters: SandboxesApiProxyToSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.proxyToSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A ttl of \"0\" removes the expiry entirely, which is how a sandbox someone is working in is kept from disappearing.
     * Reset a sandbox\'s lifetime, measured from now
     */
    async renewSandboxRaw(requestParameters: SandboxesApiRenewSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sandbox>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling renewSandbox().'
            );
        }

        if (requestParameters['renewSandboxRequest'] == null) {
            throw new runtime.RequiredError(
                'renewSandboxRequest',
                'Required parameter "renewSandboxRequest" was null or undefined when calling renewSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Sandbox-Key"] = await this.configuration.apiKey("X-Sandbox-Key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sandboxes/{id}/renew`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RenewSandboxRequestToJSON(requestParameters['renewSandboxRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxFromJSON(jsonValue));
    }

    /**
     * A ttl of \"0\" removes the expiry entirely, which is how a sandbox someone is working in is kept from disappearing.
     * Reset a sandbox\'s lifetime, measured from now
     */
    async renewSandbox(requestParameters: SandboxesApiRenewSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sandbox> {
        const response = await this.renewSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
