/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A template to add, as its YAML document. It is text rather than the Template object because the thing being sent is a document — the same shape as a catalog file — and the server parses it strictly, so an unknown field or an invalid template is a 400.
 * @export
 * @interface AddTemplateRequest
 */
export interface AddTemplateRequest {
    /**
     * the template as YAML. The id must be lowercase alphanumerics and '-'. Nothing here is persisted; the catalog returns to the compiled-in templates on restart.
     * @type {string}
     * @memberof AddTemplateRequest
     */
    document: string;
    /**
     * replace a template that already has this id instead of answering 409. Without it an existing id is a conflict, so a create that was meant to add cannot quietly overwrite.
     * @type {boolean}
     * @memberof AddTemplateRequest
     */
    overwrite?: boolean;
}

/**
 * Check if a given object implements the AddTemplateRequest interface.
 */
export function instanceOfAddTemplateRequest(value: object): value is AddTemplateRequest {
    if (!('document' in value) || value['document'] === undefined) return false;
    return true;
}

export function AddTemplateRequestFromJSON(json: any): AddTemplateRequest {
    return AddTemplateRequestFromJSONTyped(json, false);
}

export function AddTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'document': json['document'],
        'overwrite': json['overwrite'] == null ? undefined : json['overwrite'],
    };
}

export function AddTemplateRequestToJSON(json: any): AddTemplateRequest {
    return AddTemplateRequestToJSONTyped(json, false);
}

export function AddTemplateRequestToJSONTyped(value?: AddTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'document': value['document'],
        'overwrite': value['overwrite'],
    };
}

