/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSandboxRequest
 */
export interface CreateSandboxRequest {
    /**
     * the catalog id to create from
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    template: string;
    /**
     * the sandbox's name; generated when empty. Lowercase alphanumerics and '-', up to 40 characters, because it becomes a namespace.
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    name?: string;
    /**
     * how long it may live, e.g. 90m; the template's default when empty
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    ttl?: string;
    /**
     * environment overrides, merged over the template's own
     * @type {{ [key: string]: string; }}
     * @memberof CreateSandboxRequest
     */
    env?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateSandboxRequest interface.
 */
export function instanceOfCreateSandboxRequest(value: object): value is CreateSandboxRequest {
    if (!('template' in value) || value['template'] === undefined) return false;
    return true;
}

export function CreateSandboxRequestFromJSON(json: any): CreateSandboxRequest {
    return CreateSandboxRequestFromJSONTyped(json, false);
}

export function CreateSandboxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSandboxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'template': json['template'],
        'name': json['name'] == null ? undefined : json['name'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'env': json['env'] == null ? undefined : json['env'],
    };
}

export function CreateSandboxRequestToJSON(json: any): CreateSandboxRequest {
    return CreateSandboxRequestToJSONTyped(json, false);
}

export function CreateSandboxRequestToJSONTyped(value?: CreateSandboxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template': value['template'],
        'name': value['name'],
        'ttl': value['ttl'],
        'env': value['env'],
    };
}

