/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthDescription } from './AuthDescription';
import {
    AuthDescriptionFromJSON,
    AuthDescriptionFromJSONTyped,
    AuthDescriptionToJSON,
    AuthDescriptionToJSONTyped,
} from './AuthDescription';
import type { EndpointDescription } from './EndpointDescription';
import {
    EndpointDescriptionFromJSON,
    EndpointDescriptionFromJSONTyped,
    EndpointDescriptionToJSON,
    EndpointDescriptionToJSONTyped,
} from './EndpointDescription';

/**
 * 
 * @export
 * @interface Describe
 */
export interface Describe {
    /**
     * 
     * @type {string}
     * @memberof Describe
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Describe
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof Describe
     */
    build: string;
    /**
     * 
     * @type {string}
     * @memberof Describe
     */
    basePath: string;
    /**
     * 
     * @type {AuthDescription}
     * @memberof Describe
     */
    auth: AuthDescription;
    /**
     * 
     * @type {Array<EndpointDescription>}
     * @memberof Describe
     */
    endpoints: Array<EndpointDescription>;
}

/**
 * Check if a given object implements the Describe interface.
 */
export function instanceOfDescribe(value: object): value is Describe {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('build' in value) || value['build'] === undefined) return false;
    if (!('basePath' in value) || value['basePath'] === undefined) return false;
    if (!('auth' in value) || value['auth'] === undefined) return false;
    if (!('endpoints' in value) || value['endpoints'] === undefined) return false;
    return true;
}

export function DescribeFromJSON(json: any): Describe {
    return DescribeFromJSONTyped(json, false);
}

export function DescribeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Describe {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'],
        'build': json['build'],
        'basePath': json['basePath'],
        'auth': AuthDescriptionFromJSON(json['auth']),
        'endpoints': ((json['endpoints'] as Array<any>).map(EndpointDescriptionFromJSON)),
    };
}

export function DescribeToJSON(json: any): Describe {
    return DescribeToJSONTyped(json, false);
}

export function DescribeToJSONTyped(value?: Describe | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
        'build': value['build'],
        'basePath': value['basePath'],
        'auth': AuthDescriptionToJSON(value['auth']),
        'endpoints': ((value['endpoints'] as Array<any>).map(EndpointDescriptionToJSON)),
    };
}

