/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Endpoint
 */
export interface Endpoint {
    /**
     * the port name it serves
     * @type {string}
     * @memberof Endpoint
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Endpoint
     */
    port: number;
    /**
     * the address to open; absent when the deployment has no public URL
     * @type {string}
     * @memberof Endpoint
     */
    url?: string;
}

/**
 * Check if a given object implements the Endpoint interface.
 */
export function instanceOfEndpoint(value: object): value is Endpoint {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    return true;
}

export function EndpointFromJSON(json: any): Endpoint {
    return EndpointFromJSONTyped(json, false);
}

export function EndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): Endpoint {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'port': json['port'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function EndpointToJSON(json: any): Endpoint {
    return EndpointToJSONTyped(json, false);
}

export function EndpointToJSONTyped(value?: Endpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'port': value['port'],
        'url': value['url'],
    };
}

