/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecRequest
 */
export interface ExecRequest {
    /**
     * the command and its arguments, as separate values. Pass ["sh", "-c", "..."] to have a shell interpret a command line; anything else is executed directly.
     * @type {Array<string>}
     * @memberof ExecRequest
     */
    command: Array<string>;
    /**
     * input for the command, decoded per encoding
     * @type {string}
     * @memberof ExecRequest
     */
    stdin?: string;
    /**
     * the working directory; the image's own when omitted
     * @type {string}
     * @memberof ExecRequest
     */
    cwd?: string;
    /**
     * how long the command may take, e.g. "30s". Clamped to the deployment's own ceiling however large it is.
     * @type {string}
     * @memberof ExecRequest
     */
    timeout?: string;
    /**
     * how stdin is spelled; utf8 is the default
     * @type {string}
     * @memberof ExecRequest
     */
    encoding?: ExecRequestEncodingEnum;
}


/**
 * @export
 */
export const ExecRequestEncodingEnum = {
    Utf8: 'utf8',
    Base64: 'base64'
} as const;
export type ExecRequestEncodingEnum = typeof ExecRequestEncodingEnum[keyof typeof ExecRequestEncodingEnum];


/**
 * Check if a given object implements the ExecRequest interface.
 */
export function instanceOfExecRequest(value: object): value is ExecRequest {
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function ExecRequestFromJSON(json: any): ExecRequest {
    return ExecRequestFromJSONTyped(json, false);
}

export function ExecRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'command': json['command'],
        'stdin': json['stdin'] == null ? undefined : json['stdin'],
        'cwd': json['cwd'] == null ? undefined : json['cwd'],
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
        'encoding': json['encoding'] == null ? undefined : json['encoding'],
    };
}

export function ExecRequestToJSON(json: any): ExecRequest {
    return ExecRequestToJSONTyped(json, false);
}

export function ExecRequestToJSONTyped(value?: ExecRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': value['command'],
        'stdin': value['stdin'],
        'cwd': value['cwd'],
        'timeout': value['timeout'],
        'encoding': value['encoding'],
    };
}

