/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileContent
 */
export interface FileContent {
    /**
     * 
     * @type {string}
     * @memberof FileContent
     */
    path: string;
    /**
     * the file's bytes, decoded per encoding
     * @type {string}
     * @memberof FileContent
     */
    content: string;
    /**
     * utf8 when the file is valid UTF-8 text, base64 when it is not — a caller reads this rather than guessing from the content
     * @type {string}
     * @memberof FileContent
     */
    encoding: FileContentEncodingEnum;
    /**
     * the length of the file's bytes, before encoding
     * @type {number}
     * @memberof FileContent
     */
    size: number;
}


/**
 * @export
 */
export const FileContentEncodingEnum = {
    Utf8: 'utf8',
    Base64: 'base64'
} as const;
export type FileContentEncodingEnum = typeof FileContentEncodingEnum[keyof typeof FileContentEncodingEnum];


/**
 * Check if a given object implements the FileContent interface.
 */
export function instanceOfFileContent(value: object): value is FileContent {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('encoding' in value) || value['encoding'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function FileContentFromJSON(json: any): FileContent {
    return FileContentFromJSONTyped(json, false);
}

export function FileContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileContent {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'content': json['content'],
        'encoding': json['encoding'],
        'size': json['size'],
    };
}

export function FileContentToJSON(json: any): FileContent {
    return FileContentToJSONTyped(json, false);
}

export function FileContentToJSONTyped(value?: FileContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'content': value['content'],
        'encoding': value['encoding'],
        'size': value['size'],
    };
}

