/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSandboxLogs200Response
 */
export interface GetSandboxLogs200Response {
    /**
     * 
     * @type {string}
     * @memberof GetSandboxLogs200Response
     */
    logs: string;
}

/**
 * Check if a given object implements the GetSandboxLogs200Response interface.
 */
export function instanceOfGetSandboxLogs200Response(value: object): value is GetSandboxLogs200Response {
    if (!('logs' in value) || value['logs'] === undefined) return false;
    return true;
}

export function GetSandboxLogs200ResponseFromJSON(json: any): GetSandboxLogs200Response {
    return GetSandboxLogs200ResponseFromJSONTyped(json, false);
}

export function GetSandboxLogs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSandboxLogs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': json['logs'],
    };
}

export function GetSandboxLogs200ResponseToJSON(json: any): GetSandboxLogs200Response {
    return GetSandboxLogs200ResponseToJSONTyped(json, false);
}

export function GetSandboxLogs200ResponseToJSONTyped(value?: GetSandboxLogs200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logs': value['logs'],
    };
}

