/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RotateKeyRequest
 */
export interface RotateKeyRequest {
    /**
     * the new key; generated when empty
     * @type {string}
     * @memberof RotateKeyRequest
     */
    key?: string;
}

/**
 * Check if a given object implements the RotateKeyRequest interface.
 */
export function instanceOfRotateKeyRequest(value: object): value is RotateKeyRequest {
    return true;
}

export function RotateKeyRequestFromJSON(json: any): RotateKeyRequest {
    return RotateKeyRequestFromJSONTyped(json, false);
}

export function RotateKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotateKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function RotateKeyRequestToJSON(json: any): RotateKeyRequest {
    return RotateKeyRequestToJSONTyped(json, false);
}

export function RotateKeyRequestToJSONTyped(value?: RotateKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
    };
}

