/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Template } from './Template';
import {
    TemplateFromJSON,
    TemplateFromJSONTyped,
    TemplateToJSON,
    TemplateToJSONTyped,
} from './Template';

/**
 * The catalog — what a sandbox can be created from.
 * @export
 * @interface TemplateList
 */
export interface TemplateList {
    /**
     * 
     * @type {Array<Template>}
     * @memberof TemplateList
     */
    templates: Array<Template>;
}

/**
 * Check if a given object implements the TemplateList interface.
 */
export function instanceOfTemplateList(value: object): value is TemplateList {
    if (!('templates' in value) || value['templates'] === undefined) return false;
    return true;
}

export function TemplateListFromJSON(json: any): TemplateList {
    return TemplateListFromJSONTyped(json, false);
}

export function TemplateListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateList {
    if (json == null) {
        return json;
    }
    return {
        
        'templates': ((json['templates'] as Array<any>).map(TemplateFromJSON)),
    };
}

export function TemplateListToJSON(json: any): TemplateList {
    return TemplateListToJSONTyped(json, false);
}

export function TemplateListToJSONTyped(value?: TemplateList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templates': ((value['templates'] as Array<any>).map(TemplateToJSON)),
    };
}

