/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Quota } from './Quota';
import {
    QuotaFromJSON,
    QuotaFromJSONTyped,
    QuotaToJSON,
    QuotaToJSONTyped,
} from './Quota';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    name: string;
    /**
     * the credential. Present on a create, a rotate and a reveal, and omitted from a listing, so a list is safe to leave on a screen.
     * @type {string}
     * @memberof User
     */
    key?: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;
    /**
     * absent when the key has never been used, which is what an administrator most wants to know
     * @type {Date}
     * @memberof User
     */
    lastUsedAt?: Date;
    /**
     * 
     * @type {Quota}
     * @memberof User
     */
    quota: Quota;
    /**
     * how many the user has now; absent when it could not be counted
     * @type {number}
     * @memberof User
     */
    sandboxes?: number;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('quota' in value) || value['quota'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'key': json['key'] == null ? undefined : json['key'],
        'createdAt': (new Date(json['createdAt'])),
        'lastUsedAt': json['lastUsedAt'] == null ? undefined : (new Date(json['lastUsedAt'])),
        'quota': QuotaFromJSON(json['quota']),
        'sandboxes': json['sandboxes'] == null ? undefined : json['sandboxes'],
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
        'createdAt': value['createdAt'].toISOString(),
        'lastUsedAt': value['lastUsedAt'] == null ? value['lastUsedAt'] : value['lastUsedAt'].toISOString(),
        'quota': QuotaToJSON(value['quota']),
        'sandboxes': value['sandboxes'],
    };
}

