/* tslint:disable */
/* eslint-disable */
/**
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WriteFileRequest
 */
export interface WriteFileRequest {
    /**
     * the file's bytes, decoded per encoding
     * @type {string}
     * @memberof WriteFileRequest
     */
    content: string;
    /**
     * how content is spelled; utf8 is the default
     * @type {string}
     * @memberof WriteFileRequest
     */
    encoding?: WriteFileRequestEncodingEnum;
    /**
     * create the directories above the path when they are missing. Off by default, so a mistyped directory is a 400 naming it rather than a file written somewhere unexpected.
     * @type {boolean}
     * @memberof WriteFileRequest
     */
    createParents?: boolean;
}


/**
 * @export
 */
export const WriteFileRequestEncodingEnum = {
    Utf8: 'utf8',
    Base64: 'base64'
} as const;
export type WriteFileRequestEncodingEnum = typeof WriteFileRequestEncodingEnum[keyof typeof WriteFileRequestEncodingEnum];


/**
 * Check if a given object implements the WriteFileRequest interface.
 */
export function instanceOfWriteFileRequest(value: object): value is WriteFileRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function WriteFileRequestFromJSON(json: any): WriteFileRequest {
    return WriteFileRequestFromJSONTyped(json, false);
}

export function WriteFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'encoding': json['encoding'] == null ? undefined : json['encoding'],
        'createParents': json['createParents'] == null ? undefined : json['createParents'],
    };
}

export function WriteFileRequestToJSON(json: any): WriteFileRequest {
    return WriteFileRequestToJSONTyped(json, false);
}

export function WriteFileRequestToJSONTyped(value?: WriteFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'encoding': value['encoding'],
        'createParents': value['createParents'],
    };
}

