/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sandboxlab.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.sandboxlab.client.ApiClient;
/**
 * A template to add, as its YAML document. It is text rather than the Template object because the thing being sent is a document — the same shape as a catalog file — and the server parses it strictly, so an unknown field or an invalid template is a 400.
 */
@JsonPropertyOrder({
  AddTemplateRequest.JSON_PROPERTY_DOCUMENT,
  AddTemplateRequest.JSON_PROPERTY_OVERWRITE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AddTemplateRequest {
  public static final String JSON_PROPERTY_DOCUMENT = "document";
  @javax.annotation.Nonnull
  private String document;

  public static final String JSON_PROPERTY_OVERWRITE = "overwrite";
  @javax.annotation.Nullable
  private Boolean overwrite;

  public AddTemplateRequest() { 
  }

  public AddTemplateRequest document(@javax.annotation.Nonnull String document) {
    this.document = document;
    return this;
  }

  /**
   * the template as YAML. The id must be lowercase alphanumerics and &#39;-&#39;. Nothing here is persisted; the catalog returns to the compiled-in templates on restart.
   * @return document
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOCUMENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDocument() {
    return document;
  }


  @JsonProperty(value = JSON_PROPERTY_DOCUMENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocument(@javax.annotation.Nonnull String document) {
    this.document = document;
  }


  public AddTemplateRequest overwrite(@javax.annotation.Nullable Boolean overwrite) {
    this.overwrite = overwrite;
    return this;
  }

  /**
   * replace a template that already has this id instead of answering 409. Without it an existing id is a conflict, so a create that was meant to add cannot quietly overwrite.
   * @return overwrite
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OVERWRITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getOverwrite() {
    return overwrite;
  }


  @JsonProperty(value = JSON_PROPERTY_OVERWRITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverwrite(@javax.annotation.Nullable Boolean overwrite) {
    this.overwrite = overwrite;
  }


  /**
   * Return true if this AddTemplateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddTemplateRequest addTemplateRequest = (AddTemplateRequest) o;
    return Objects.equals(this.document, addTemplateRequest.document) &&
        Objects.equals(this.overwrite, addTemplateRequest.overwrite);
  }

  @Override
  public int hashCode() {
    return Objects.hash(document, overwrite);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddTemplateRequest {\n");
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    overwrite: ").append(toIndentedString(overwrite)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `document` to the URL query string
    if (getDocument() != null) {
      joiner.add(String.format(Locale.ROOT, "%sdocument%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDocument()))));
    }

    // add `overwrite` to the URL query string
    if (getOverwrite() != null) {
      joiner.add(String.format(Locale.ROOT, "%soverwrite%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOverwrite()))));
    }

    return joiner.toString();
  }
}

