/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sandboxlab.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.sandboxlab.client.ApiClient;
/**
 * CreateSandboxRequest
 */
@JsonPropertyOrder({
  CreateSandboxRequest.JSON_PROPERTY_TEMPLATE,
  CreateSandboxRequest.JSON_PROPERTY_NAME,
  CreateSandboxRequest.JSON_PROPERTY_TTL,
  CreateSandboxRequest.JSON_PROPERTY_ENV
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CreateSandboxRequest {
  public static final String JSON_PROPERTY_TEMPLATE = "template";
  @javax.annotation.Nonnull
  private String template;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_TTL = "ttl";
  @javax.annotation.Nullable
  private String ttl;

  public static final String JSON_PROPERTY_ENV = "env";
  @javax.annotation.Nullable
  private Map<String, String> env = new HashMap<>();

  public CreateSandboxRequest() { 
  }

  public CreateSandboxRequest template(@javax.annotation.Nonnull String template) {
    this.template = template;
    return this;
  }

  /**
   * the catalog id to create from
   * @return template
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTemplate() {
    return template;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemplate(@javax.annotation.Nonnull String template) {
    this.template = template;
  }


  public CreateSandboxRequest name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * the sandbox&#39;s name; generated when empty. Lowercase alphanumerics and &#39;-&#39;, up to 40 characters, because it becomes a namespace.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CreateSandboxRequest ttl(@javax.annotation.Nullable String ttl) {
    this.ttl = ttl;
    return this;
  }

  /**
   * how long it may live, e.g. 90m; the template&#39;s default when empty
   * @return ttl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TTL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTtl() {
    return ttl;
  }


  @JsonProperty(value = JSON_PROPERTY_TTL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTtl(@javax.annotation.Nullable String ttl) {
    this.ttl = ttl;
  }


  public CreateSandboxRequest env(@javax.annotation.Nullable Map<String, String> env) {
    this.env = env;
    return this;
  }

  public CreateSandboxRequest putEnvItem(String key, String envItem) {
    if (this.env == null) {
      this.env = new HashMap<>();
    }
    this.env.put(key, envItem);
    return this;
  }

  /**
   * environment overrides, merged over the template&#39;s own
   * @return env
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENV, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getEnv() {
    return env;
  }


  @JsonProperty(value = JSON_PROPERTY_ENV, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnv(@javax.annotation.Nullable Map<String, String> env) {
    this.env = env;
  }


  /**
   * Return true if this CreateSandboxRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSandboxRequest createSandboxRequest = (CreateSandboxRequest) o;
    return Objects.equals(this.template, createSandboxRequest.template) &&
        Objects.equals(this.name, createSandboxRequest.name) &&
        Objects.equals(this.ttl, createSandboxRequest.ttl) &&
        Objects.equals(this.env, createSandboxRequest.env);
  }

  @Override
  public int hashCode() {
    return Objects.hash(template, name, ttl, env);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSandboxRequest {\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ttl: ").append(toIndentedString(ttl)).append("\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `template` to the URL query string
    if (getTemplate() != null) {
      joiner.add(String.format(Locale.ROOT, "%stemplate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemplate()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `ttl` to the URL query string
    if (getTtl() != null) {
      joiner.add(String.format(Locale.ROOT, "%sttl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTtl()))));
    }

    // add `env` to the URL query string
    if (getEnv() != null) {
      for (String _key : getEnv().keySet()) {
        joiner.add(String.format(Locale.ROOT, "%senv%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getEnv().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getEnv().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

