/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sandboxlab.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sandboxlab.model.AuthDescription;
import com.sandboxlab.model.EndpointDescription;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.sandboxlab.client.ApiClient;
/**
 * Describe
 */
@JsonPropertyOrder({
  Describe.JSON_PROPERTY_NAME,
  Describe.JSON_PROPERTY_VERSION,
  Describe.JSON_PROPERTY_BUILD,
  Describe.JSON_PROPERTY_BASE_PATH,
  Describe.JSON_PROPERTY_AUTH,
  Describe.JSON_PROPERTY_ENDPOINTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Describe {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nonnull
  private String version;

  public static final String JSON_PROPERTY_BUILD = "build";
  @javax.annotation.Nonnull
  private String build;

  public static final String JSON_PROPERTY_BASE_PATH = "basePath";
  @javax.annotation.Nonnull
  private String basePath;

  public static final String JSON_PROPERTY_AUTH = "auth";
  @javax.annotation.Nonnull
  private AuthDescription auth;

  public static final String JSON_PROPERTY_ENDPOINTS = "endpoints";
  @javax.annotation.Nonnull
  private List<EndpointDescription> endpoints = new ArrayList<>();

  public Describe() { 
  }

  public Describe name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public Describe version(@javax.annotation.Nonnull String version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@javax.annotation.Nonnull String version) {
    this.version = version;
  }


  public Describe build(@javax.annotation.Nonnull String build) {
    this.build = build;
    return this;
  }

  /**
   * Get build
   * @return build
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUILD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBuild() {
    return build;
  }


  @JsonProperty(value = JSON_PROPERTY_BUILD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBuild(@javax.annotation.Nonnull String build) {
    this.build = build;
  }


  public Describe basePath(@javax.annotation.Nonnull String basePath) {
    this.basePath = basePath;
    return this;
  }

  /**
   * Get basePath
   * @return basePath
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BASE_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBasePath() {
    return basePath;
  }


  @JsonProperty(value = JSON_PROPERTY_BASE_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBasePath(@javax.annotation.Nonnull String basePath) {
    this.basePath = basePath;
  }


  public Describe auth(@javax.annotation.Nonnull AuthDescription auth) {
    this.auth = auth;
    return this;
  }

  /**
   * Get auth
   * @return auth
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AuthDescription getAuth() {
    return auth;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuth(@javax.annotation.Nonnull AuthDescription auth) {
    this.auth = auth;
  }


  public Describe endpoints(@javax.annotation.Nonnull List<EndpointDescription> endpoints) {
    this.endpoints = endpoints;
    return this;
  }

  public Describe addEndpointsItem(EndpointDescription endpointsItem) {
    if (this.endpoints == null) {
      this.endpoints = new ArrayList<>();
    }
    this.endpoints.add(endpointsItem);
    return this;
  }

  /**
   * Get endpoints
   * @return endpoints
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENDPOINTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<EndpointDescription> getEndpoints() {
    return endpoints;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndpoints(@javax.annotation.Nonnull List<EndpointDescription> endpoints) {
    this.endpoints = endpoints;
  }


  /**
   * Return true if this Describe object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Describe describe = (Describe) o;
    return Objects.equals(this.name, describe.name) &&
        Objects.equals(this.version, describe.version) &&
        Objects.equals(this.build, describe.build) &&
        Objects.equals(this.basePath, describe.basePath) &&
        Objects.equals(this.auth, describe.auth) &&
        Objects.equals(this.endpoints, describe.endpoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, version, build, basePath, auth, endpoints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Describe {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    build: ").append(toIndentedString(build)).append("\n");
    sb.append("    basePath: ").append(toIndentedString(basePath)).append("\n");
    sb.append("    auth: ").append(toIndentedString(auth)).append("\n");
    sb.append("    endpoints: ").append(toIndentedString(endpoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `version` to the URL query string
    if (getVersion() != null) {
      joiner.add(String.format(Locale.ROOT, "%sversion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersion()))));
    }

    // add `build` to the URL query string
    if (getBuild() != null) {
      joiner.add(String.format(Locale.ROOT, "%sbuild%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBuild()))));
    }

    // add `basePath` to the URL query string
    if (getBasePath() != null) {
      joiner.add(String.format(Locale.ROOT, "%sbasePath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBasePath()))));
    }

    // add `auth` to the URL query string
    if (getAuth() != null) {
      joiner.add(getAuth().toUrlQueryString(prefix + "auth" + suffix));
    }

    // add `endpoints` to the URL query string
    if (getEndpoints() != null) {
      for (int i = 0; i < getEndpoints().size(); i++) {
        if (getEndpoints().get(i) != null) {
          joiner.add(getEndpoints().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sendpoints%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

