/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sandboxlab.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.sandboxlab.client.ApiClient;
/**
 * ExecResult
 */
@JsonPropertyOrder({
  ExecResult.JSON_PROPERTY_EXIT_CODE,
  ExecResult.JSON_PROPERTY_STDOUT,
  ExecResult.JSON_PROPERTY_STDERR,
  ExecResult.JSON_PROPERTY_STDOUT_ENCODING,
  ExecResult.JSON_PROPERTY_STDERR_ENCODING,
  ExecResult.JSON_PROPERTY_STDOUT_TRUNCATED,
  ExecResult.JSON_PROPERTY_STDERR_TRUNCATED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ExecResult {
  public static final String JSON_PROPERTY_EXIT_CODE = "exitCode";
  @javax.annotation.Nonnull
  private Integer exitCode;

  public static final String JSON_PROPERTY_STDOUT = "stdout";
  @javax.annotation.Nonnull
  private String stdout;

  public static final String JSON_PROPERTY_STDERR = "stderr";
  @javax.annotation.Nonnull
  private String stderr;

  /**
   * how stdout is spelled: utf8 for text, base64 for anything that is not valid UTF-8. Chosen per stream, so a command that printed text to one and bytes to the other is spelled correctly in both.
   */
  public enum StdoutEncodingEnum {
    UTF8(String.valueOf("utf8")),
    
    BASE64(String.valueOf("base64"));

    private String value;

    StdoutEncodingEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StdoutEncodingEnum fromValue(String value) {
      for (StdoutEncodingEnum b : StdoutEncodingEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STDOUT_ENCODING = "stdoutEncoding";
  @javax.annotation.Nonnull
  private StdoutEncodingEnum stdoutEncoding;

  /**
   * Gets or Sets stderrEncoding
   */
  public enum StderrEncodingEnum {
    UTF8(String.valueOf("utf8")),
    
    BASE64(String.valueOf("base64"));

    private String value;

    StderrEncodingEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StderrEncodingEnum fromValue(String value) {
      for (StderrEncodingEnum b : StderrEncodingEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STDERR_ENCODING = "stderrEncoding";
  @javax.annotation.Nonnull
  private StderrEncodingEnum stderrEncoding;

  public static final String JSON_PROPERTY_STDOUT_TRUNCATED = "stdoutTruncated";
  @javax.annotation.Nullable
  private Boolean stdoutTruncated;

  public static final String JSON_PROPERTY_STDERR_TRUNCATED = "stderrTruncated";
  @javax.annotation.Nullable
  private Boolean stderrTruncated;

  public ExecResult() { 
  }

  public ExecResult exitCode(@javax.annotation.Nonnull Integer exitCode) {
    this.exitCode = exitCode;
    return this;
  }

  /**
   * the command&#39;s exit status. A non-zero value is not a failure of this request: the command ran. Only an error response means it could not be run.
   * @return exitCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXIT_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getExitCode() {
    return exitCode;
  }


  @JsonProperty(value = JSON_PROPERTY_EXIT_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExitCode(@javax.annotation.Nonnull Integer exitCode) {
    this.exitCode = exitCode;
  }


  public ExecResult stdout(@javax.annotation.Nonnull String stdout) {
    this.stdout = stdout;
    return this;
  }

  /**
   * Get stdout
   * @return stdout
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STDOUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getStdout() {
    return stdout;
  }


  @JsonProperty(value = JSON_PROPERTY_STDOUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStdout(@javax.annotation.Nonnull String stdout) {
    this.stdout = stdout;
  }


  public ExecResult stderr(@javax.annotation.Nonnull String stderr) {
    this.stderr = stderr;
    return this;
  }

  /**
   * Get stderr
   * @return stderr
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STDERR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getStderr() {
    return stderr;
  }


  @JsonProperty(value = JSON_PROPERTY_STDERR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStderr(@javax.annotation.Nonnull String stderr) {
    this.stderr = stderr;
  }


  public ExecResult stdoutEncoding(@javax.annotation.Nonnull StdoutEncodingEnum stdoutEncoding) {
    this.stdoutEncoding = stdoutEncoding;
    return this;
  }

  /**
   * how stdout is spelled: utf8 for text, base64 for anything that is not valid UTF-8. Chosen per stream, so a command that printed text to one and bytes to the other is spelled correctly in both.
   * @return stdoutEncoding
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STDOUT_ENCODING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StdoutEncodingEnum getStdoutEncoding() {
    return stdoutEncoding;
  }


  @JsonProperty(value = JSON_PROPERTY_STDOUT_ENCODING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStdoutEncoding(@javax.annotation.Nonnull StdoutEncodingEnum stdoutEncoding) {
    this.stdoutEncoding = stdoutEncoding;
  }


  public ExecResult stderrEncoding(@javax.annotation.Nonnull StderrEncodingEnum stderrEncoding) {
    this.stderrEncoding = stderrEncoding;
    return this;
  }

  /**
   * Get stderrEncoding
   * @return stderrEncoding
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STDERR_ENCODING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StderrEncodingEnum getStderrEncoding() {
    return stderrEncoding;
  }


  @JsonProperty(value = JSON_PROPERTY_STDERR_ENCODING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStderrEncoding(@javax.annotation.Nonnull StderrEncodingEnum stderrEncoding) {
    this.stderrEncoding = stderrEncoding;
  }


  public ExecResult stdoutTruncated(@javax.annotation.Nullable Boolean stdoutTruncated) {
    this.stdoutTruncated = stdoutTruncated;
    return this;
  }

  /**
   * the output hit the deployment&#39;s cap and was cut off
   * @return stdoutTruncated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STDOUT_TRUNCATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getStdoutTruncated() {
    return stdoutTruncated;
  }


  @JsonProperty(value = JSON_PROPERTY_STDOUT_TRUNCATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStdoutTruncated(@javax.annotation.Nullable Boolean stdoutTruncated) {
    this.stdoutTruncated = stdoutTruncated;
  }


  public ExecResult stderrTruncated(@javax.annotation.Nullable Boolean stderrTruncated) {
    this.stderrTruncated = stderrTruncated;
    return this;
  }

  /**
   * Get stderrTruncated
   * @return stderrTruncated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STDERR_TRUNCATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getStderrTruncated() {
    return stderrTruncated;
  }


  @JsonProperty(value = JSON_PROPERTY_STDERR_TRUNCATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStderrTruncated(@javax.annotation.Nullable Boolean stderrTruncated) {
    this.stderrTruncated = stderrTruncated;
  }


  /**
   * Return true if this ExecResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecResult execResult = (ExecResult) o;
    return Objects.equals(this.exitCode, execResult.exitCode) &&
        Objects.equals(this.stdout, execResult.stdout) &&
        Objects.equals(this.stderr, execResult.stderr) &&
        Objects.equals(this.stdoutEncoding, execResult.stdoutEncoding) &&
        Objects.equals(this.stderrEncoding, execResult.stderrEncoding) &&
        Objects.equals(this.stdoutTruncated, execResult.stdoutTruncated) &&
        Objects.equals(this.stderrTruncated, execResult.stderrTruncated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exitCode, stdout, stderr, stdoutEncoding, stderrEncoding, stdoutTruncated, stderrTruncated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecResult {\n");
    sb.append("    exitCode: ").append(toIndentedString(exitCode)).append("\n");
    sb.append("    stdout: ").append(toIndentedString(stdout)).append("\n");
    sb.append("    stderr: ").append(toIndentedString(stderr)).append("\n");
    sb.append("    stdoutEncoding: ").append(toIndentedString(stdoutEncoding)).append("\n");
    sb.append("    stderrEncoding: ").append(toIndentedString(stderrEncoding)).append("\n");
    sb.append("    stdoutTruncated: ").append(toIndentedString(stdoutTruncated)).append("\n");
    sb.append("    stderrTruncated: ").append(toIndentedString(stderrTruncated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `exitCode` to the URL query string
    if (getExitCode() != null) {
      joiner.add(String.format(Locale.ROOT, "%sexitCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExitCode()))));
    }

    // add `stdout` to the URL query string
    if (getStdout() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstdout%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStdout()))));
    }

    // add `stderr` to the URL query string
    if (getStderr() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstderr%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStderr()))));
    }

    // add `stdoutEncoding` to the URL query string
    if (getStdoutEncoding() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstdoutEncoding%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStdoutEncoding()))));
    }

    // add `stderrEncoding` to the URL query string
    if (getStderrEncoding() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstderrEncoding%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStderrEncoding()))));
    }

    // add `stdoutTruncated` to the URL query string
    if (getStdoutTruncated() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstdoutTruncated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStdoutTruncated()))));
    }

    // add `stderrTruncated` to the URL query string
    if (getStderrTruncated() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstderrTruncated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStderrTruncated()))));
    }

    return joiner.toString();
  }
}

