/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sandboxlab.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.sandboxlab.client.ApiClient;
/**
 * ExecRequest
 */
@JsonPropertyOrder({
  ExecRequest.JSON_PROPERTY_COMMAND,
  ExecRequest.JSON_PROPERTY_STDIN,
  ExecRequest.JSON_PROPERTY_CWD,
  ExecRequest.JSON_PROPERTY_TIMEOUT,
  ExecRequest.JSON_PROPERTY_ENCODING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ExecRequest {
  public static final String JSON_PROPERTY_COMMAND = "command";
  @javax.annotation.Nonnull
  private List<String> command = new ArrayList<>();

  public static final String JSON_PROPERTY_STDIN = "stdin";
  @javax.annotation.Nullable
  private String stdin;

  public static final String JSON_PROPERTY_CWD = "cwd";
  @javax.annotation.Nullable
  private String cwd;

  public static final String JSON_PROPERTY_TIMEOUT = "timeout";
  @javax.annotation.Nullable
  private String timeout;

  /**
   * how stdin is spelled; utf8 is the default
   */
  public enum EncodingEnum {
    UTF8(String.valueOf("utf8")),
    
    BASE64(String.valueOf("base64"));

    private String value;

    EncodingEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EncodingEnum fromValue(String value) {
      for (EncodingEnum b : EncodingEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ENCODING = "encoding";
  @javax.annotation.Nullable
  private EncodingEnum encoding;

  public ExecRequest() { 
  }

  public ExecRequest command(@javax.annotation.Nonnull List<String> command) {
    this.command = command;
    return this;
  }

  public ExecRequest addCommandItem(String commandItem) {
    if (this.command == null) {
      this.command = new ArrayList<>();
    }
    this.command.add(commandItem);
    return this;
  }

  /**
   * the command and its arguments, as separate values. Pass [\&quot;sh\&quot;, \&quot;-c\&quot;, \&quot;...\&quot;] to have a shell interpret a command line; anything else is executed directly.
   * @return command
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getCommand() {
    return command;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCommand(@javax.annotation.Nonnull List<String> command) {
    this.command = command;
  }


  public ExecRequest stdin(@javax.annotation.Nullable String stdin) {
    this.stdin = stdin;
    return this;
  }

  /**
   * input for the command, decoded per encoding
   * @return stdin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STDIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStdin() {
    return stdin;
  }


  @JsonProperty(value = JSON_PROPERTY_STDIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStdin(@javax.annotation.Nullable String stdin) {
    this.stdin = stdin;
  }


  public ExecRequest cwd(@javax.annotation.Nullable String cwd) {
    this.cwd = cwd;
    return this;
  }

  /**
   * the working directory; the image&#39;s own when omitted
   * @return cwd
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CWD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCwd() {
    return cwd;
  }


  @JsonProperty(value = JSON_PROPERTY_CWD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCwd(@javax.annotation.Nullable String cwd) {
    this.cwd = cwd;
  }


  public ExecRequest timeout(@javax.annotation.Nullable String timeout) {
    this.timeout = timeout;
    return this;
  }

  /**
   * how long the command may take, e.g. \&quot;30s\&quot;. Clamped to the deployment&#39;s own ceiling however large it is.
   * @return timeout
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEOUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimeout() {
    return timeout;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEOUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeout(@javax.annotation.Nullable String timeout) {
    this.timeout = timeout;
  }


  public ExecRequest encoding(@javax.annotation.Nullable EncodingEnum encoding) {
    this.encoding = encoding;
    return this;
  }

  /**
   * how stdin is spelled; utf8 is the default
   * @return encoding
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENCODING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EncodingEnum getEncoding() {
    return encoding;
  }


  @JsonProperty(value = JSON_PROPERTY_ENCODING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncoding(@javax.annotation.Nullable EncodingEnum encoding) {
    this.encoding = encoding;
  }


  /**
   * Return true if this ExecRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecRequest execRequest = (ExecRequest) o;
    return Objects.equals(this.command, execRequest.command) &&
        Objects.equals(this.stdin, execRequest.stdin) &&
        Objects.equals(this.cwd, execRequest.cwd) &&
        Objects.equals(this.timeout, execRequest.timeout) &&
        Objects.equals(this.encoding, execRequest.encoding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(command, stdin, cwd, timeout, encoding);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecRequest {\n");
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    stdin: ").append(toIndentedString(stdin)).append("\n");
    sb.append("    cwd: ").append(toIndentedString(cwd)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    encoding: ").append(toIndentedString(encoding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `command` to the URL query string
    if (getCommand() != null) {
      for (int i = 0; i < getCommand().size(); i++) {
        joiner.add(String.format(Locale.ROOT, "%scommand%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCommand().get(i)))));
      }
    }

    // add `stdin` to the URL query string
    if (getStdin() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstdin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStdin()))));
    }

    // add `cwd` to the URL query string
    if (getCwd() != null) {
      joiner.add(String.format(Locale.ROOT, "%scwd%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCwd()))));
    }

    // add `timeout` to the URL query string
    if (getTimeout() != null) {
      joiner.add(String.format(Locale.ROOT, "%stimeout%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimeout()))));
    }

    // add `encoding` to the URL query string
    if (getEncoding() != null) {
      joiner.add(String.format(Locale.ROOT, "%sencoding%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEncoding()))));
    }

    return joiner.toString();
  }
}

