/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sandboxlab.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.sandboxlab.client.ApiClient;
/**
 * GetSandboxLogs200Response
 */
@JsonPropertyOrder({
  GetSandboxLogs200Response.JSON_PROPERTY_LOGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GetSandboxLogs200Response {
  public static final String JSON_PROPERTY_LOGS = "logs";
  @javax.annotation.Nonnull
  private String logs;

  public GetSandboxLogs200Response() { 
  }

  public GetSandboxLogs200Response logs(@javax.annotation.Nonnull String logs) {
    this.logs = logs;
    return this;
  }

  /**
   * Get logs
   * @return logs
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOGS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLogs() {
    return logs;
  }


  @JsonProperty(value = JSON_PROPERTY_LOGS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLogs(@javax.annotation.Nonnull String logs) {
    this.logs = logs;
  }


  /**
   * Return true if this getSandboxLogs_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSandboxLogs200Response getSandboxLogs200Response = (GetSandboxLogs200Response) o;
    return Objects.equals(this.logs, getSandboxLogs200Response.logs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSandboxLogs200Response {\n");
    sb.append("    logs: ").append(toIndentedString(logs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `logs` to the URL query string
    if (getLogs() != null) {
      joiner.add(String.format(Locale.ROOT, "%slogs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLogs()))));
    }

    return joiner.toString();
  }
}

