/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sandboxlab.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.sandboxlab.client.ApiClient;
/**
 * Usage
 */
@JsonPropertyOrder({
  Usage.JSON_PROPERTY_AVAILABLE,
  Usage.JSON_PROPERTY_CPU,
  Usage.JSON_PROPERTY_MEMORY,
  Usage.JSON_PROPERTY_TIMESTAMP
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Usage {
  public static final String JSON_PROPERTY_AVAILABLE = "available";
  @javax.annotation.Nonnull
  private Boolean available;

  public static final String JSON_PROPERTY_CPU = "cpu";
  @javax.annotation.Nullable
  private String cpu;

  public static final String JSON_PROPERTY_MEMORY = "memory";
  @javax.annotation.Nullable
  private String memory;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private String timestamp;

  public Usage() { 
  }

  public Usage available(@javax.annotation.Nonnull Boolean available) {
    this.available = available;
    return this;
  }

  /**
   * whether the cluster could report usage at all. False on a cluster with no metrics-server; the reading is then absent rather than zero.
   * @return available
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AVAILABLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getAvailable() {
    return available;
  }


  @JsonProperty(value = JSON_PROPERTY_AVAILABLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAvailable(@javax.annotation.Nonnull Boolean available) {
    this.available = available;
  }


  public Usage cpu(@javax.annotation.Nullable String cpu) {
    this.cpu = cpu;
    return this;
  }

  /**
   * e.g. \&quot;12m\&quot;; a Kubernetes quantity
   * @return cpu
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CPU, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCpu() {
    return cpu;
  }


  @JsonProperty(value = JSON_PROPERTY_CPU, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCpu(@javax.annotation.Nullable String cpu) {
    this.cpu = cpu;
  }


  public Usage memory(@javax.annotation.Nullable String memory) {
    this.memory = memory;
    return this;
  }

  /**
   * e.g. \&quot;48Mi\&quot;; a Kubernetes quantity
   * @return memory
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEMORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMemory() {
    return memory;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemory(@javax.annotation.Nullable String memory) {
    this.memory = memory;
  }


  public Usage timestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * when the sample was taken
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
  }


  /**
   * Return true if this Usage object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Usage usage = (Usage) o;
    return Objects.equals(this.available, usage.available) &&
        Objects.equals(this.cpu, usage.cpu) &&
        Objects.equals(this.memory, usage.memory) &&
        Objects.equals(this.timestamp, usage.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(available, cpu, memory, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Usage {\n");
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `available` to the URL query string
    if (getAvailable() != null) {
      joiner.add(String.format(Locale.ROOT, "%savailable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAvailable()))));
    }

    // add `cpu` to the URL query string
    if (getCpu() != null) {
      joiner.add(String.format(Locale.ROOT, "%scpu%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCpu()))));
    }

    // add `memory` to the URL query string
    if (getMemory() != null) {
      joiner.add(String.format(Locale.ROOT, "%smemory%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMemory()))));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    return joiner.toString();
  }
}

