/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sandboxlab.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.sandboxlab.client.ApiClient;
/**
 * UserRequest
 */
@JsonPropertyOrder({
  UserRequest.JSON_PROPERTY_NAME,
  UserRequest.JSON_PROPERTY_KEY,
  UserRequest.JSON_PROPERTY_MAX_SANDBOXES,
  UserRequest.JSON_PROPERTY_MAX_T_T_L,
  UserRequest.JSON_PROPERTY_TEMPLATES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class UserRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_KEY = "key";
  @javax.annotation.Nullable
  private String key;

  public static final String JSON_PROPERTY_MAX_SANDBOXES = "maxSandboxes";
  @javax.annotation.Nullable
  private Integer maxSandboxes;

  public static final String JSON_PROPERTY_MAX_T_T_L = "maxTTL";
  @javax.annotation.Nullable
  private String maxTTL;

  public static final String JSON_PROPERTY_TEMPLATES = "templates";
  @javax.annotation.Nullable
  private List<String> templates = new ArrayList<>();

  public UserRequest() { 
  }

  public UserRequest name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * the user&#39;s name; only read when creating
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public UserRequest key(@javax.annotation.Nullable String key) {
    this.key = key;
    return this;
  }

  /**
   * the key to use; generated when empty
   * @return key
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(@javax.annotation.Nullable String key) {
    this.key = key;
  }


  public UserRequest maxSandboxes(@javax.annotation.Nullable Integer maxSandboxes) {
    this.maxSandboxes = maxSandboxes;
    return this;
  }

  /**
   * an omitted field leaves the current limit alone
   * @return maxSandboxes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_SANDBOXES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxSandboxes() {
    return maxSandboxes;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_SANDBOXES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxSandboxes(@javax.annotation.Nullable Integer maxSandboxes) {
    this.maxSandboxes = maxSandboxes;
  }


  public UserRequest maxTTL(@javax.annotation.Nullable String maxTTL) {
    this.maxTTL = maxTTL;
    return this;
  }

  /**
   * a duration string like \&quot;30m\&quot;; an empty string removes the limit, and an omitted field leaves it alone
   * @return maxTTL
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_T_T_L, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMaxTTL() {
    return maxTTL;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_T_T_L, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxTTL(@javax.annotation.Nullable String maxTTL) {
    this.maxTTL = maxTTL;
  }


  public UserRequest templates(@javax.annotation.Nullable List<String> templates) {
    this.templates = templates;
    return this;
  }

  public UserRequest addTemplatesItem(String templatesItem) {
    if (this.templates == null) {
      this.templates = new ArrayList<>();
    }
    this.templates.add(templatesItem);
    return this;
  }

  /**
   * an omitted field leaves the current list alone
   * @return templates
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPLATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getTemplates() {
    return templates;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplates(@javax.annotation.Nullable List<String> templates) {
    this.templates = templates;
  }


  /**
   * Return true if this UserRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserRequest userRequest = (UserRequest) o;
    return Objects.equals(this.name, userRequest.name) &&
        Objects.equals(this.key, userRequest.key) &&
        Objects.equals(this.maxSandboxes, userRequest.maxSandboxes) &&
        Objects.equals(this.maxTTL, userRequest.maxTTL) &&
        Objects.equals(this.templates, userRequest.templates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, key, maxSandboxes, maxTTL, templates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    maxSandboxes: ").append(toIndentedString(maxSandboxes)).append("\n");
    sb.append("    maxTTL: ").append(toIndentedString(maxTTL)).append("\n");
    sb.append("    templates: ").append(toIndentedString(templates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format(Locale.ROOT, "%skey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKey()))));
    }

    // add `maxSandboxes` to the URL query string
    if (getMaxSandboxes() != null) {
      joiner.add(String.format(Locale.ROOT, "%smaxSandboxes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxSandboxes()))));
    }

    // add `maxTTL` to the URL query string
    if (getMaxTTL() != null) {
      joiner.add(String.format(Locale.ROOT, "%smaxTTL%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxTTL()))));
    }

    // add `templates` to the URL query string
    if (getTemplates() != null) {
      for (int i = 0; i < getTemplates().size(); i++) {
        joiner.add(String.format(Locale.ROOT, "%stemplates%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTemplates().get(i)))));
      }
    }

    return joiner.toString();
  }
}

