/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sandboxlab.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.sandboxlab.client.ApiClient;
/**
 * Whoami
 */
@JsonPropertyOrder({
  Whoami.JSON_PROPERTY_ROLE,
  Whoami.JSON_PROPERTY_ADMIN,
  Whoami.JSON_PROPERTY_USER,
  Whoami.JSON_PROPERTY_CAN_MANAGE_USERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Whoami {
  /**
   * Gets or Sets role
   */
  public enum RoleEnum {
    ADMIN(String.valueOf("admin")),
    
    USER(String.valueOf("user"));

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RoleEnum fromValue(String value) {
      for (RoleEnum b : RoleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nonnull
  private RoleEnum role;

  public static final String JSON_PROPERTY_ADMIN = "admin";
  @javax.annotation.Nonnull
  private Boolean admin;

  public static final String JSON_PROPERTY_USER = "user";
  @javax.annotation.Nullable
  private String user;

  public static final String JSON_PROPERTY_CAN_MANAGE_USERS = "canManageUsers";
  @javax.annotation.Nullable
  private Boolean canManageUsers;

  public Whoami() { 
  }

  public Whoami role(@javax.annotation.Nonnull RoleEnum role) {
    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RoleEnum getRole() {
    return role;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRole(@javax.annotation.Nonnull RoleEnum role) {
    this.role = role;
  }


  public Whoami admin(@javax.annotation.Nonnull Boolean admin) {
    this.admin = admin;
    return this;
  }

  /**
   * Get admin
   * @return admin
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ADMIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getAdmin() {
    return admin;
  }


  @JsonProperty(value = JSON_PROPERTY_ADMIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdmin(@javax.annotation.Nonnull Boolean admin) {
    this.admin = admin;
  }


  public Whoami user(@javax.annotation.Nullable String user) {
    this.user = user;
    return this;
  }

  /**
   * the user&#39;s name; absent for the administrator
   * @return user
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUser() {
    return user;
  }


  @JsonProperty(value = JSON_PROPERTY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(@javax.annotation.Nullable String user) {
    this.user = user;
  }


  public Whoami canManageUsers(@javax.annotation.Nullable Boolean canManageUsers) {
    this.canManageUsers = canManageUsers;
    return this;
  }

  /**
   * whether this caller may read and write the user list
   * @return canManageUsers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CAN_MANAGE_USERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCanManageUsers() {
    return canManageUsers;
  }


  @JsonProperty(value = JSON_PROPERTY_CAN_MANAGE_USERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanManageUsers(@javax.annotation.Nullable Boolean canManageUsers) {
    this.canManageUsers = canManageUsers;
  }


  /**
   * Return true if this Whoami object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Whoami whoami = (Whoami) o;
    return Objects.equals(this.role, whoami.role) &&
        Objects.equals(this.admin, whoami.admin) &&
        Objects.equals(this.user, whoami.user) &&
        Objects.equals(this.canManageUsers, whoami.canManageUsers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(role, admin, user, canManageUsers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Whoami {\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    admin: ").append(toIndentedString(admin)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    canManageUsers: ").append(toIndentedString(canManageUsers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `role` to the URL query string
    if (getRole() != null) {
      joiner.add(String.format(Locale.ROOT, "%srole%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRole()))));
    }

    // add `admin` to the URL query string
    if (getAdmin() != null) {
      joiner.add(String.format(Locale.ROOT, "%sadmin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAdmin()))));
    }

    // add `user` to the URL query string
    if (getUser() != null) {
      joiner.add(String.format(Locale.ROOT, "%suser%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUser()))));
    }

    // add `canManageUsers` to the URL query string
    if (getCanManageUsers() != null) {
      joiner.add(String.format(Locale.ROOT, "%scanManageUsers%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCanManageUsers()))));
    }

    return joiner.toString();
  }
}

