/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sandboxlab.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.sandboxlab.client.ApiClient;
/**
 * WriteFileRequest
 */
@JsonPropertyOrder({
  WriteFileRequest.JSON_PROPERTY_CONTENT,
  WriteFileRequest.JSON_PROPERTY_ENCODING,
  WriteFileRequest.JSON_PROPERTY_CREATE_PARENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class WriteFileRequest {
  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nonnull
  private String content;

  /**
   * how content is spelled; utf8 is the default
   */
  public enum EncodingEnum {
    UTF8(String.valueOf("utf8")),
    
    BASE64(String.valueOf("base64"));

    private String value;

    EncodingEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EncodingEnum fromValue(String value) {
      for (EncodingEnum b : EncodingEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ENCODING = "encoding";
  @javax.annotation.Nullable
  private EncodingEnum encoding;

  public static final String JSON_PROPERTY_CREATE_PARENTS = "createParents";
  @javax.annotation.Nullable
  private Boolean createParents;

  public WriteFileRequest() { 
  }

  public WriteFileRequest content(@javax.annotation.Nonnull String content) {
    this.content = content;
    return this;
  }

  /**
   * the file&#39;s bytes, decoded per encoding
   * @return content
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@javax.annotation.Nonnull String content) {
    this.content = content;
  }


  public WriteFileRequest encoding(@javax.annotation.Nullable EncodingEnum encoding) {
    this.encoding = encoding;
    return this;
  }

  /**
   * how content is spelled; utf8 is the default
   * @return encoding
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENCODING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EncodingEnum getEncoding() {
    return encoding;
  }


  @JsonProperty(value = JSON_PROPERTY_ENCODING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncoding(@javax.annotation.Nullable EncodingEnum encoding) {
    this.encoding = encoding;
  }


  public WriteFileRequest createParents(@javax.annotation.Nullable Boolean createParents) {
    this.createParents = createParents;
    return this;
  }

  /**
   * create the directories above the path when they are missing. Off by default, so a mistyped directory is a 400 naming it rather than a file written somewhere unexpected.
   * @return createParents
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATE_PARENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCreateParents() {
    return createParents;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATE_PARENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateParents(@javax.annotation.Nullable Boolean createParents) {
    this.createParents = createParents;
  }


  /**
   * Return true if this WriteFileRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WriteFileRequest writeFileRequest = (WriteFileRequest) o;
    return Objects.equals(this.content, writeFileRequest.content) &&
        Objects.equals(this.encoding, writeFileRequest.encoding) &&
        Objects.equals(this.createParents, writeFileRequest.createParents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, encoding, createParents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WriteFileRequest {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    encoding: ").append(toIndentedString(encoding)).append("\n");
    sb.append("    createParents: ").append(toIndentedString(createParents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `content` to the URL query string
    if (getContent() != null) {
      joiner.add(String.format(Locale.ROOT, "%scontent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContent()))));
    }

    // add `encoding` to the URL query string
    if (getEncoding() != null) {
      joiner.add(String.format(Locale.ROOT, "%sencoding%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEncoding()))));
    }

    // add `createParents` to the URL query string
    if (getCreateParents() != null) {
      joiner.add(String.format(Locale.ROOT, "%screateParents%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreateParents()))));
    }

    return joiner.toString();
  }
}

