{{- if .Values.catalog }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sandbox.fullname" . }}-catalog
  namespace: {{ include "sandbox.namespace" . }}
  labels:
    {{- include "sandbox.labels" . | nindent 4 }}
data:
  {{- range $name, $document := .Values.catalog }}
  {{ $name }}: |
    {{- $document | nindent 4 }}
  {{- end }}
{{- end }}
