# coding: utf-8

"""
    sandboxlab

    Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Overview(BaseModel):
    """
    Overview
    """ # noqa: E501
    total: StrictInt
    by_state: Dict[str, StrictInt] = Field(alias="byState")
    by_template: Dict[str, StrictInt] = Field(alias="byTemplate")
    by_owner: Optional[Dict[str, StrictInt]] = Field(default=None, alias="byOwner")
    cluster: StrictBool = Field(description="whether the cluster is reachable")
    max_sandboxes: Optional[StrictInt] = Field(default=None, description="the deployment's ceiling; 0 means none", alias="maxSandboxes")
    user: Optional[StrictStr] = Field(default=None, description="whose sandboxes these are, when the view is a user's rather than the deployment's")
    scoped: StrictBool = Field(description="whether the view is a user's rather than the deployment's")
    __properties: ClassVar[List[str]] = ["total", "byState", "byTemplate", "byOwner", "cluster", "maxSandboxes", "user", "scoped"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Overview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Overview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total": obj.get("total"),
            "byState": obj.get("byState"),
            "byTemplate": obj.get("byTemplate"),
            "byOwner": obj.get("byOwner"),
            "cluster": obj.get("cluster"),
            "maxSandboxes": obj.get("maxSandboxes"),
            "user": obj.get("user"),
            "scoped": obj.get("scoped")
        })
        return _obj


