/*
 * sandboxlab
 * Create disposable sandbox environments — a shell, a filesystem, a browser — on demand, in Kubernetes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sandboxlab.api;

import com.sandboxlab.client.ApiClient;
import com.sandboxlab.client.ApiException;
import com.sandboxlab.client.ApiResponse;
import com.sandboxlab.client.Configuration;
import com.sandboxlab.client.Pair;

import com.sandboxlab.model.CreateSandboxRequest;
import com.sandboxlab.model.DeleteSandbox200Response;
import com.sandboxlab.model.Error;
import com.sandboxlab.model.ExecRequest;
import com.sandboxlab.model.ExecResult;
import java.io.File;
import com.sandboxlab.model.FileContent;
import com.sandboxlab.model.FileInfo;
import com.sandboxlab.model.GetSandboxLogs200Response;
import com.sandboxlab.model.Overview;
import com.sandboxlab.model.RenewSandboxRequest;
import com.sandboxlab.model.Sandbox;
import com.sandboxlab.model.SandboxList;
import com.sandboxlab.model.Template;
import com.sandboxlab.model.TemplateList;
import com.sandboxlab.model.WriteFileRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class SandboxesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public SandboxesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public SandboxesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create one
   * 
   * @param createSandboxRequest  (required)
   * @return Sandbox
   * @throws ApiException if fails to make API call
   */
  public Sandbox createSandbox(@javax.annotation.Nonnull CreateSandboxRequest createSandboxRequest) throws ApiException {
    return createSandbox(createSandboxRequest, null);
  }

  /**
   * Create one
   * 
   * @param createSandboxRequest  (required)
   * @param headers Optional headers to include in the request
   * @return Sandbox
   * @throws ApiException if fails to make API call
   */
  public Sandbox createSandbox(@javax.annotation.Nonnull CreateSandboxRequest createSandboxRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<Sandbox> localVarResponse = createSandboxWithHttpInfo(createSandboxRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Create one
   * 
   * @param createSandboxRequest  (required)
   * @return ApiResponse&lt;Sandbox&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Sandbox> createSandboxWithHttpInfo(@javax.annotation.Nonnull CreateSandboxRequest createSandboxRequest) throws ApiException {
    return createSandboxWithHttpInfo(createSandboxRequest, null);
  }

  /**
   * Create one
   * 
   * @param createSandboxRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Sandbox&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Sandbox> createSandboxWithHttpInfo(@javax.annotation.Nonnull CreateSandboxRequest createSandboxRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createSandboxRequestBuilder(createSandboxRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createSandbox", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Sandbox>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        Sandbox responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Sandbox>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<Sandbox>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createSandboxRequestBuilder(@javax.annotation.Nonnull CreateSandboxRequest createSandboxRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createSandboxRequest' is set
    if (createSandboxRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createSandboxRequest' when calling createSandbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/sandboxes";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createSandboxRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete one
   * Everything in it goes too. A sandbox is a namespace, so this is one operation rather than a list of objects to get right.
   * @param id  (required)
   * @return DeleteSandbox200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteSandbox200Response deleteSandbox(@javax.annotation.Nonnull String id) throws ApiException {
    return deleteSandbox(id, null);
  }

  /**
   * Delete one
   * Everything in it goes too. A sandbox is a namespace, so this is one operation rather than a list of objects to get right.
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return DeleteSandbox200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteSandbox200Response deleteSandbox(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<DeleteSandbox200Response> localVarResponse = deleteSandboxWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Delete one
   * Everything in it goes too. A sandbox is a namespace, so this is one operation rather than a list of objects to get right.
   * @param id  (required)
   * @return ApiResponse&lt;DeleteSandbox200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteSandbox200Response> deleteSandboxWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return deleteSandboxWithHttpInfo(id, null);
  }

  /**
   * Delete one
   * Everything in it goes too. A sandbox is a namespace, so this is one operation rather than a list of objects to get right.
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DeleteSandbox200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteSandbox200Response> deleteSandboxWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteSandboxRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteSandbox", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<DeleteSandbox200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        DeleteSandbox200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DeleteSandbox200Response>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<DeleteSandbox200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteSandboxRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteSandbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/sandboxes/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Run a command in a sandbox and wait for it
   * The command is an argv, not a command line: pass [\&quot;sh\&quot;, \&quot;-c\&quot;, \&quot;...\&quot;] to have a shell interpret it, and pass anything else to have it not. This is the way into a sandbox whose template serves no port — python and node are a workspace with no URL, and this is what reaches them.  **A non-zero exitCode is not a failure.** The command ran and that is what it returned, so the response is a 200 carrying the output and the status. Only an error response means the command could not be run at all — no pod yet, no permission, or the timeout below.
   * @param id  (required)
   * @param execRequest  (required)
   * @return ExecResult
   * @throws ApiException if fails to make API call
   */
  public ExecResult execInSandbox(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull ExecRequest execRequest) throws ApiException {
    return execInSandbox(id, execRequest, null);
  }

  /**
   * Run a command in a sandbox and wait for it
   * The command is an argv, not a command line: pass [\&quot;sh\&quot;, \&quot;-c\&quot;, \&quot;...\&quot;] to have a shell interpret it, and pass anything else to have it not. This is the way into a sandbox whose template serves no port — python and node are a workspace with no URL, and this is what reaches them.  **A non-zero exitCode is not a failure.** The command ran and that is what it returned, so the response is a 200 carrying the output and the status. Only an error response means the command could not be run at all — no pod yet, no permission, or the timeout below.
   * @param id  (required)
   * @param execRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ExecResult
   * @throws ApiException if fails to make API call
   */
  public ExecResult execInSandbox(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull ExecRequest execRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<ExecResult> localVarResponse = execInSandboxWithHttpInfo(id, execRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Run a command in a sandbox and wait for it
   * The command is an argv, not a command line: pass [\&quot;sh\&quot;, \&quot;-c\&quot;, \&quot;...\&quot;] to have a shell interpret it, and pass anything else to have it not. This is the way into a sandbox whose template serves no port — python and node are a workspace with no URL, and this is what reaches them.  **A non-zero exitCode is not a failure.** The command ran and that is what it returned, so the response is a 200 carrying the output and the status. Only an error response means the command could not be run at all — no pod yet, no permission, or the timeout below.
   * @param id  (required)
   * @param execRequest  (required)
   * @return ApiResponse&lt;ExecResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ExecResult> execInSandboxWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull ExecRequest execRequest) throws ApiException {
    return execInSandboxWithHttpInfo(id, execRequest, null);
  }

  /**
   * Run a command in a sandbox and wait for it
   * The command is an argv, not a command line: pass [\&quot;sh\&quot;, \&quot;-c\&quot;, \&quot;...\&quot;] to have a shell interpret it, and pass anything else to have it not. This is the way into a sandbox whose template serves no port — python and node are a workspace with no URL, and this is what reaches them.  **A non-zero exitCode is not a failure.** The command ran and that is what it returned, so the response is a 200 carrying the output and the status. Only an error response means the command could not be run at all — no pod yet, no permission, or the timeout below.
   * @param id  (required)
   * @param execRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ExecResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ExecResult> execInSandboxWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull ExecRequest execRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = execInSandboxRequestBuilder(id, execRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("execInSandbox", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<ExecResult>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        ExecResult responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ExecResult>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<ExecResult>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder execInSandboxRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull ExecRequest execRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling execInSandbox");
    }
    // verify the required parameter 'execRequest' is set
    if (execRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'execRequest' when calling execInSandbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/sandboxes/{id}/exec"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(execRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * One template
   * 
   * @param id  (required)
   * @return Template
   * @throws ApiException if fails to make API call
   */
  public Template getCatalogEntry(@javax.annotation.Nonnull String id) throws ApiException {
    return getCatalogEntry(id, null);
  }

  /**
   * One template
   * 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return Template
   * @throws ApiException if fails to make API call
   */
  public Template getCatalogEntry(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<Template> localVarResponse = getCatalogEntryWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * One template
   * 
   * @param id  (required)
   * @return ApiResponse&lt;Template&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Template> getCatalogEntryWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return getCatalogEntryWithHttpInfo(id, null);
  }

  /**
   * One template
   * 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Template&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Template> getCatalogEntryWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getCatalogEntryRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getCatalogEntry", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Template>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        Template responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Template>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<Template>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCatalogEntryRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getCatalogEntry");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/catalog/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Counts of sandboxes by state and template
   * What is running and what it is: how many sandboxes exist, and how they break down by state and template.
   * @return Overview
   * @throws ApiException if fails to make API call
   */
  public Overview getOverview() throws ApiException {
    return getOverview(null);
  }

  /**
   * Counts of sandboxes by state and template
   * What is running and what it is: how many sandboxes exist, and how they break down by state and template.
   * @param headers Optional headers to include in the request
   * @return Overview
   * @throws ApiException if fails to make API call
   */
  public Overview getOverview(Map<String, String> headers) throws ApiException {
    ApiResponse<Overview> localVarResponse = getOverviewWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Counts of sandboxes by state and template
   * What is running and what it is: how many sandboxes exist, and how they break down by state and template.
   * @return ApiResponse&lt;Overview&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Overview> getOverviewWithHttpInfo() throws ApiException {
    return getOverviewWithHttpInfo(null);
  }

  /**
   * Counts of sandboxes by state and template
   * What is running and what it is: how many sandboxes exist, and how they break down by state and template.
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Overview&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Overview> getOverviewWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getOverviewRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getOverview", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Overview>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        Overview responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Overview>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<Overview>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getOverviewRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/overview";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * One sandbox
   * 
   * @param id  (required)
   * @return Sandbox
   * @throws ApiException if fails to make API call
   */
  public Sandbox getSandbox(@javax.annotation.Nonnull String id) throws ApiException {
    return getSandbox(id, null);
  }

  /**
   * One sandbox
   * 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return Sandbox
   * @throws ApiException if fails to make API call
   */
  public Sandbox getSandbox(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<Sandbox> localVarResponse = getSandboxWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * One sandbox
   * 
   * @param id  (required)
   * @return ApiResponse&lt;Sandbox&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Sandbox> getSandboxWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return getSandboxWithHttpInfo(id, null);
  }

  /**
   * One sandbox
   * 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Sandbox&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Sandbox> getSandboxWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSandboxRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSandbox", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Sandbox>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        Sandbox responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Sandbox>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<Sandbox>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSandboxRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getSandbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/sandboxes/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * The tail of a sandbox&#39;s output
   * A sandbox whose container is still being created answers 409: there is nothing to read yet, which is the ordinary state moments after a create rather than a failure.
   * @param id  (required)
   * @param tail how many lines to return; 200 when omitted (optional)
   * @return GetSandboxLogs200Response
   * @throws ApiException if fails to make API call
   */
  public GetSandboxLogs200Response getSandboxLogs(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer tail) throws ApiException {
    return getSandboxLogs(id, tail, null);
  }

  /**
   * The tail of a sandbox&#39;s output
   * A sandbox whose container is still being created answers 409: there is nothing to read yet, which is the ordinary state moments after a create rather than a failure.
   * @param id  (required)
   * @param tail how many lines to return; 200 when omitted (optional)
   * @param headers Optional headers to include in the request
   * @return GetSandboxLogs200Response
   * @throws ApiException if fails to make API call
   */
  public GetSandboxLogs200Response getSandboxLogs(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer tail, Map<String, String> headers) throws ApiException {
    ApiResponse<GetSandboxLogs200Response> localVarResponse = getSandboxLogsWithHttpInfo(id, tail, headers);
    return localVarResponse.getData();
  }

  /**
   * The tail of a sandbox&#39;s output
   * A sandbox whose container is still being created answers 409: there is nothing to read yet, which is the ordinary state moments after a create rather than a failure.
   * @param id  (required)
   * @param tail how many lines to return; 200 when omitted (optional)
   * @return ApiResponse&lt;GetSandboxLogs200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetSandboxLogs200Response> getSandboxLogsWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer tail) throws ApiException {
    return getSandboxLogsWithHttpInfo(id, tail, null);
  }

  /**
   * The tail of a sandbox&#39;s output
   * A sandbox whose container is still being created answers 409: there is nothing to read yet, which is the ordinary state moments after a create rather than a failure.
   * @param id  (required)
   * @param tail how many lines to return; 200 when omitted (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetSandboxLogs200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetSandboxLogs200Response> getSandboxLogsWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer tail, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSandboxLogsRequestBuilder(id, tail, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSandboxLogs", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<GetSandboxLogs200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        GetSandboxLogs200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetSandboxLogs200Response>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<GetSandboxLogs200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSandboxLogsRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer tail, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getSandboxLogs");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/sandboxes/{id}/logs"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "tail";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("tail", tail));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * The templates a sandbox can be created from
   * 
   * @return TemplateList
   * @throws ApiException if fails to make API call
   */
  public TemplateList listCatalog() throws ApiException {
    return listCatalog(null);
  }

  /**
   * The templates a sandbox can be created from
   * 
   * @param headers Optional headers to include in the request
   * @return TemplateList
   * @throws ApiException if fails to make API call
   */
  public TemplateList listCatalog(Map<String, String> headers) throws ApiException {
    ApiResponse<TemplateList> localVarResponse = listCatalogWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * The templates a sandbox can be created from
   * 
   * @return ApiResponse&lt;TemplateList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TemplateList> listCatalogWithHttpInfo() throws ApiException {
    return listCatalogWithHttpInfo(null);
  }

  /**
   * The templates a sandbox can be created from
   * 
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TemplateList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TemplateList> listCatalogWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listCatalogRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listCatalog", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<TemplateList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        TemplateList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TemplateList>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<TemplateList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listCatalogRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/catalog";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Every sandbox in the deployment
   * 
   * @return SandboxList
   * @throws ApiException if fails to make API call
   */
  public SandboxList listSandboxes() throws ApiException {
    return listSandboxes(null);
  }

  /**
   * Every sandbox in the deployment
   * 
   * @param headers Optional headers to include in the request
   * @return SandboxList
   * @throws ApiException if fails to make API call
   */
  public SandboxList listSandboxes(Map<String, String> headers) throws ApiException {
    ApiResponse<SandboxList> localVarResponse = listSandboxesWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Every sandbox in the deployment
   * 
   * @return ApiResponse&lt;SandboxList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SandboxList> listSandboxesWithHttpInfo() throws ApiException {
    return listSandboxesWithHttpInfo(null);
  }

  /**
   * Every sandbox in the deployment
   * 
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SandboxList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SandboxList> listSandboxesWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listSandboxesRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listSandboxes", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<SandboxList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        SandboxList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<SandboxList>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<SandboxList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listSandboxesRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/sandboxes";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Proxy to a sandbox&#39;s own port
   * The data plane: everything under this prefix is forwarded to the sandbox&#39;s container. What comes back is whatever the sandbox serves — HTML, JSON, a file — so it is not a typed endpoint and the SDK exposes the address rather than a method. A browser navigation cannot set a header, which is why the key is also accepted in the query string.
   * @param id  (required)
   * @param port  (required)
   * @return File
   * @throws ApiException if fails to make API call
   */
  public File proxyToSandbox(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String port) throws ApiException {
    return proxyToSandbox(id, port, null);
  }

  /**
   * Proxy to a sandbox&#39;s own port
   * The data plane: everything under this prefix is forwarded to the sandbox&#39;s container. What comes back is whatever the sandbox serves — HTML, JSON, a file — so it is not a typed endpoint and the SDK exposes the address rather than a method. A browser navigation cannot set a header, which is why the key is also accepted in the query string.
   * @param id  (required)
   * @param port  (required)
   * @param headers Optional headers to include in the request
   * @return File
   * @throws ApiException if fails to make API call
   */
  public File proxyToSandbox(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String port, Map<String, String> headers) throws ApiException {
    ApiResponse<File> localVarResponse = proxyToSandboxWithHttpInfo(id, port, headers);
    return localVarResponse.getData();
  }

  /**
   * Proxy to a sandbox&#39;s own port
   * The data plane: everything under this prefix is forwarded to the sandbox&#39;s container. What comes back is whatever the sandbox serves — HTML, JSON, a file — so it is not a typed endpoint and the SDK exposes the address rather than a method. A browser navigation cannot set a header, which is why the key is also accepted in the query string.
   * @param id  (required)
   * @param port  (required)
   * @return ApiResponse&lt;File&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<File> proxyToSandboxWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String port) throws ApiException {
    return proxyToSandboxWithHttpInfo(id, port, null);
  }

  /**
   * Proxy to a sandbox&#39;s own port
   * The data plane: everything under this prefix is forwarded to the sandbox&#39;s container. What comes back is whatever the sandbox serves — HTML, JSON, a file — so it is not a typed endpoint and the SDK exposes the address rather than a method. A browser navigation cannot set a header, which is why the key is also accepted in the query string.
   * @param id  (required)
   * @param port  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;File&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<File> proxyToSandboxWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String port, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = proxyToSandboxRequestBuilder(id, port, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("proxyToSandbox", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<File>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        // Handle file downloading.
        File responseValue = downloadFileFromResponse(localVarResponse);
        
        localVarResponse.body().close();

        return new ApiResponse<File>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder proxyToSandboxRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String port, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling proxyToSandbox");
    }
    // verify the required parameter 'port' is set
    if (port == null) {
      throw new ApiException(400, "Missing the required parameter 'port' when calling proxyToSandbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/sandbox/{id}/{port}/"
        .replace("{id}", ApiClient.urlEncode(id.toString()))
        .replace("{port}", ApiClient.urlEncode(port.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*, application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Read a file out of a sandbox
   * content is the file&#39;s bytes: UTF-8 verbatim when the file is text, and base64 when it is not. encoding says which, so a caller reads a field rather than sniffing the content. A file over the deployment&#39;s limit is 413 rather than a truncated read.
   * @param id  (required)
   * @param path an absolute path inside the sandbox (required)
   * @return FileContent
   * @throws ApiException if fails to make API call
   */
  public FileContent readSandboxFile(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String path) throws ApiException {
    return readSandboxFile(id, path, null);
  }

  /**
   * Read a file out of a sandbox
   * content is the file&#39;s bytes: UTF-8 verbatim when the file is text, and base64 when it is not. encoding says which, so a caller reads a field rather than sniffing the content. A file over the deployment&#39;s limit is 413 rather than a truncated read.
   * @param id  (required)
   * @param path an absolute path inside the sandbox (required)
   * @param headers Optional headers to include in the request
   * @return FileContent
   * @throws ApiException if fails to make API call
   */
  public FileContent readSandboxFile(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String path, Map<String, String> headers) throws ApiException {
    ApiResponse<FileContent> localVarResponse = readSandboxFileWithHttpInfo(id, path, headers);
    return localVarResponse.getData();
  }

  /**
   * Read a file out of a sandbox
   * content is the file&#39;s bytes: UTF-8 verbatim when the file is text, and base64 when it is not. encoding says which, so a caller reads a field rather than sniffing the content. A file over the deployment&#39;s limit is 413 rather than a truncated read.
   * @param id  (required)
   * @param path an absolute path inside the sandbox (required)
   * @return ApiResponse&lt;FileContent&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FileContent> readSandboxFileWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String path) throws ApiException {
    return readSandboxFileWithHttpInfo(id, path, null);
  }

  /**
   * Read a file out of a sandbox
   * content is the file&#39;s bytes: UTF-8 verbatim when the file is text, and base64 when it is not. encoding says which, so a caller reads a field rather than sniffing the content. A file over the deployment&#39;s limit is 413 rather than a truncated read.
   * @param id  (required)
   * @param path an absolute path inside the sandbox (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;FileContent&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FileContent> readSandboxFileWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String path, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = readSandboxFileRequestBuilder(id, path, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("readSandboxFile", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<FileContent>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        FileContent responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<FileContent>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<FileContent>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder readSandboxFileRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String path, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling readSandboxFile");
    }
    // verify the required parameter 'path' is set
    if (path == null) {
      throw new ApiException(400, "Missing the required parameter 'path' when calling readSandboxFile");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/sandboxes/{id}/files"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "path";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("path", path));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Reset a sandbox&#39;s lifetime, measured from now
   * A ttl of \&quot;0\&quot; removes the expiry entirely, which is how a sandbox someone is working in is kept from disappearing.
   * @param id  (required)
   * @param renewSandboxRequest  (required)
   * @return Sandbox
   * @throws ApiException if fails to make API call
   */
  public Sandbox renewSandbox(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull RenewSandboxRequest renewSandboxRequest) throws ApiException {
    return renewSandbox(id, renewSandboxRequest, null);
  }

  /**
   * Reset a sandbox&#39;s lifetime, measured from now
   * A ttl of \&quot;0\&quot; removes the expiry entirely, which is how a sandbox someone is working in is kept from disappearing.
   * @param id  (required)
   * @param renewSandboxRequest  (required)
   * @param headers Optional headers to include in the request
   * @return Sandbox
   * @throws ApiException if fails to make API call
   */
  public Sandbox renewSandbox(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull RenewSandboxRequest renewSandboxRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<Sandbox> localVarResponse = renewSandboxWithHttpInfo(id, renewSandboxRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Reset a sandbox&#39;s lifetime, measured from now
   * A ttl of \&quot;0\&quot; removes the expiry entirely, which is how a sandbox someone is working in is kept from disappearing.
   * @param id  (required)
   * @param renewSandboxRequest  (required)
   * @return ApiResponse&lt;Sandbox&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Sandbox> renewSandboxWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull RenewSandboxRequest renewSandboxRequest) throws ApiException {
    return renewSandboxWithHttpInfo(id, renewSandboxRequest, null);
  }

  /**
   * Reset a sandbox&#39;s lifetime, measured from now
   * A ttl of \&quot;0\&quot; removes the expiry entirely, which is how a sandbox someone is working in is kept from disappearing.
   * @param id  (required)
   * @param renewSandboxRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Sandbox&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Sandbox> renewSandboxWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull RenewSandboxRequest renewSandboxRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = renewSandboxRequestBuilder(id, renewSandboxRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("renewSandbox", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Sandbox>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        Sandbox responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Sandbox>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<Sandbox>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder renewSandboxRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull RenewSandboxRequest renewSandboxRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling renewSandbox");
    }
    // verify the required parameter 'renewSandboxRequest' is set
    if (renewSandboxRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'renewSandboxRequest' when calling renewSandbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/sandboxes/{id}/renew"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(renewSandboxRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Write a file into a sandbox
   * It creates the file if it is absent and replaces it if it is. Parent directories are not created unless createParents is set: a silently created directory turns a mistyped path into a file nobody will find, where a refusal names the directory that is missing.
   * @param id  (required)
   * @param path an absolute path inside the sandbox (required)
   * @param writeFileRequest  (required)
   * @return FileInfo
   * @throws ApiException if fails to make API call
   */
  public FileInfo writeSandboxFile(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String path, @javax.annotation.Nonnull WriteFileRequest writeFileRequest) throws ApiException {
    return writeSandboxFile(id, path, writeFileRequest, null);
  }

  /**
   * Write a file into a sandbox
   * It creates the file if it is absent and replaces it if it is. Parent directories are not created unless createParents is set: a silently created directory turns a mistyped path into a file nobody will find, where a refusal names the directory that is missing.
   * @param id  (required)
   * @param path an absolute path inside the sandbox (required)
   * @param writeFileRequest  (required)
   * @param headers Optional headers to include in the request
   * @return FileInfo
   * @throws ApiException if fails to make API call
   */
  public FileInfo writeSandboxFile(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String path, @javax.annotation.Nonnull WriteFileRequest writeFileRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<FileInfo> localVarResponse = writeSandboxFileWithHttpInfo(id, path, writeFileRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Write a file into a sandbox
   * It creates the file if it is absent and replaces it if it is. Parent directories are not created unless createParents is set: a silently created directory turns a mistyped path into a file nobody will find, where a refusal names the directory that is missing.
   * @param id  (required)
   * @param path an absolute path inside the sandbox (required)
   * @param writeFileRequest  (required)
   * @return ApiResponse&lt;FileInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FileInfo> writeSandboxFileWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String path, @javax.annotation.Nonnull WriteFileRequest writeFileRequest) throws ApiException {
    return writeSandboxFileWithHttpInfo(id, path, writeFileRequest, null);
  }

  /**
   * Write a file into a sandbox
   * It creates the file if it is absent and replaces it if it is. Parent directories are not created unless createParents is set: a silently created directory turns a mistyped path into a file nobody will find, where a refusal names the directory that is missing.
   * @param id  (required)
   * @param path an absolute path inside the sandbox (required)
   * @param writeFileRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;FileInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FileInfo> writeSandboxFileWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String path, @javax.annotation.Nonnull WriteFileRequest writeFileRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = writeSandboxFileRequestBuilder(id, path, writeFileRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("writeSandboxFile", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<FileInfo>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        FileInfo responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<FileInfo>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<FileInfo>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder writeSandboxFileRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String path, @javax.annotation.Nonnull WriteFileRequest writeFileRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling writeSandboxFile");
    }
    // verify the required parameter 'path' is set
    if (path == null) {
      throw new ApiException(400, "Missing the required parameter 'path' when calling writeSandboxFile");
    }
    // verify the required parameter 'writeFileRequest' is set
    if (writeFileRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'writeFileRequest' when calling writeSandboxFile");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/sandboxes/{id}/files"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "path";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("path", path));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(writeFileRequest);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
